// Test-only fixture — do not import in production code
import type { MenuItemDto } from "@/features/menu/types"

export const menuMock: MenuItemDto[] = [
  {
    id: "1",
    name: "Grilled Mediterranean Sea Bass",
    description: "Fresh sea bass with herbs, lemon, and olive oil",
    price: 28.5,
    category: "mains",
    image: "/grilled-sea-bass-mediterranean.jpg",
    dietary: ["gluten-free"],
    ingredients: ["Sea bass", "Olive oil", "Lemon", "Fresh herbs", "Garlic"],
    allergens: ["Fish"],
    popular: true,
  },
  {
    id: "2",
    name: "Truffle Risotto",
    description: "Creamy arborio rice with black truffle and parmesan",
    price: 24.0,
    category: "mains",
    image: "/truffle-risotto-creamy.jpg",
    dietary: ["vegetarian"],
    ingredients: ["Arborio rice", "Black truffle", "Parmesan", "White wine", "Butter"],
    allergens: ["Dairy", "Gluten"],
  },
  {
    id: "3",
    name: "Burrata Caprese",
    description: "Fresh burrata with heirloom tomatoes and basil",
    price: 16.0,
    category: "starters",
    image: "/burrata-caprese-tomatoes.jpg",
    dietary: ["vegetarian"],
    ingredients: ["Burrata cheese", "Heirloom tomatoes", "Fresh basil", "Balsamic glaze"],
    allergens: ["Dairy"],
  },
  {
    id: "4",
    name: "Lamb Tagine",
    description: "Slow-cooked lamb with apricots and Moroccan spices",
    price: 32.0,
    category: "mains",
    image: "/moroccan-lamb-tagine.png",
    dietary: ["halal"],
    ingredients: ["Lamb shoulder", "Dried apricots", "Moroccan spices", "Onions", "Almonds"],
    allergens: ["Nuts"],
  },
  {
    id: "5",
    name: "Chocolate Soufflé",
    description: "Warm chocolate soufflé with vanilla ice cream",
    price: 12.0,
    category: "desserts",
    image: "/chocolate-souffle.png",
    dietary: ["vegetarian"],
    ingredients: ["Dark chocolate", "Eggs", "Sugar", "Butter", "Vanilla"],
    allergens: ["Eggs", "Dairy", "Gluten"],
  },
  {
    id: "6",
    name: "Quinoa Buddha Bowl",
    description: "Nutritious bowl with quinoa, roasted vegetables, and tahini",
    price: 18.0,
    category: "mains",
    image: "/quinoa-buddha-bowl-healthy.jpg",
    dietary: ["vegan", "gluten-free"],
    ingredients: ["Quinoa", "Roasted vegetables", "Tahini", "Chickpeas", "Avocado"],
    allergens: ["Sesame"],
  },
  {
    id: "8",
    name: "Fresh Mint Tea",
    description: "Traditional Moroccan mint tea",
    price: 5.0,
    category: "drinks",
    image: "/moroccan-mint-tea.png",
    dietary: ["vegan", "gluten-free"],
    ingredients: ["Green tea", "Fresh mint", "Sugar"],
    allergens: [],
  },
]
