/**
 * @file Test-only fixture. Do not import from production code.
 * Used by unit/integration tests.
 */
import type { MenuItemDto } from '../types';

export const menuMock: MenuItemDto[] = [
  {
    id: '1',
    name: 'Grilled Mediterranean Sea Bass',
    description: 'Fresh sea bass with herbs, lemon, and olive oil',
    price_cents: 2850,
    category: 'mains',
    image_url: '/grilled-sea-bass-mediterranean.jpg',
    dietary_tags: ['gluten-free'],
    ingredients: ['Sea bass', 'Olive oil', 'Lemon', 'Fresh herbs', 'Garlic'],
    allergens: ['Fish'],
    is_popular: true,
  },
  {
    id: '2',
    name: 'Truffle Risotto',
    description: 'Creamy arborio rice with black truffle and parmesan',
    price_cents: 2400,
    category: 'mains',
    image_url: '/truffle-risotto-creamy.jpg',
    dietary_tags: ['vegetarian'],
    ingredients: ['Arborio rice', 'Black truffle', 'Parmesan', 'White wine', 'Butter'],
    allergens: ['Dairy', 'Gluten'],
  },
  {
    id: '3',
    name: 'Burrata Caprese',
    description: 'Fresh burrata with heirloom tomatoes and basil',
    price_cents: 1600,
    category: 'starters',
    image_url: '/burrata-caprese-tomatoes.jpg',
    dietary_tags: ['vegetarian'],
    ingredients: ['Burrata cheese', 'Heirloom tomatoes', 'Fresh basil', 'Balsamic glaze'],
    allergens: ['Dairy'],
  },
  {
    id: '4',
    name: 'Lamb Tagine',
    description: 'Slow-cooked lamb with apricots and Moroccan spices',
    price_cents: 3200,
    category: 'mains',
    image_url: '/moroccan-lamb-tagine.png',
    dietary_tags: ['halal'],
    ingredients: ['Lamb shoulder', 'Dried apricots', 'Moroccan spices', 'Onions', 'Almonds'],
    allergens: ['Nuts'],
  },
  {
    id: '5',
    name: 'Chocolate Soufflé',
    description: 'Warm chocolate soufflé with vanilla ice cream',
    price_cents: 1200,
    category: 'desserts',
    image_url: '/chocolate-souffle.png',
    dietary_tags: ['vegetarian'],
    ingredients: ['Dark chocolate', 'Eggs', 'Sugar', 'Butter', 'Vanilla'],
    allergens: ['Eggs', 'Dairy', 'Gluten'],
  },
  {
    id: '6',
    name: 'Quinoa Buddha Bowl',
    description: 'Nutritious bowl with quinoa, roasted vegetables, and tahini',
    price_cents: 1800,
    category: 'mains',
    image_url: '/quinoa-buddha-bowl-healthy.jpg',
    dietary_tags: ['vegan', 'gluten-free'],
    ingredients: ['Quinoa', 'Roasted vegetables', 'Tahini', 'Chickpeas', 'Avocado'],
    allergens: ['Sesame'],
  },
  {
    id: '8',
    name: 'Fresh Mint Tea',
    description: 'Traditional Moroccan mint tea',
    price_cents: 500,
    category: 'drinks',
    image_url: '/moroccan-mint-tea.png',
    dietary_tags: ['vegan', 'gluten-free'],
    ingredients: ['Green tea', 'Fresh mint', 'Sugar'],
    allergens: [],
  },
];
